/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

@class DVTFilePath, DVTPlatform, DVTSearchPath, NSArray, NSDictionary, NSNumber, NSString, NSURL;

@interface DVTSDK : NSObject

@property(readonly, copy) NSArray *toolchainNames; 
@property(readonly, copy) NSDictionary *defaultProperties; 
@property(readonly, copy) NSArray *toolchains; 
@property(readonly, copy) NSURL *docSetFeedURL; 
@property(readonly, copy) NSString *docSetFeedName; 
@property(readonly, copy) NSArray *librarySearchPaths; 
@property(readonly, copy) NSString *alternateSDKName; 
@property(readonly, copy) NSArray *supportedBuildToolComponents; 
@property(readonly, copy) NSString *propertyConditionName; 
@property(readonly, copy) NSString *minimalDisplayName; 
@property(readonly, copy) NSString *displayName; 
@property(readonly, copy) NSString *canonicalName; 
@property(readonly, copy) DVTFilePath *sdkPath; 
@property(readonly, copy) NSDictionary *infoDictionary; 
@property(readonly, copy) NSString *operatingSystemVersion;
@property(readonly) NSDictionary *versionInfo; 
@property(readonly, getter=isBaseSDK) BOOL baseSDK;
@property(readonly, getter=isInternal) BOOL internal;
@property(retain) DVTPlatform *platform;

+ (id)sdksInDirectory:(id)arg1 forPlatform:(id)arg2;
+ (id)sdkInDirectory:(id)arg1 forPlatform:(id)arg2;
+ (id)sdkForPath:(id)arg1 forceCreate:(BOOL)arg2;
+ (id)sdkForPath:(id)arg1;
+ (BOOL)sdkForBootSystemRequiresSpecialTreatment;
+ (id)sdkForBootSystemOrNil;
+ (id)sdkForBootSystem;
+ (id)sdkForNameOrPath:(id)arg1 withBasePath:(id)arg2 forceCreate:(BOOL)arg3;
+ (id)_localizedSDKNameForCanonicalName:(id)arg1;
+ (id)_localizedFamilyNameForCanonicalName:(id)arg1;
+ (id)_absolutePathForSDKPathString:(id)arg1;
+ (id)sdksForFamily:(id)arg1;
+ (id)sdkForCanonicalName:(id)arg1;
+ (void)_setSDK:(id)arg1 forCanonicalName:(id)arg2;
+ (id)_sdkForResolvedAbsolutePath:(id)arg1;
+ (void)_setSDK:(id)arg1 forResolvedAbsolutePath:(id)arg2;
+ (id)knownSDKs;
+ (BOOL)shouldAllowBootSystemSDK;
+ (void)initialize;

- (id)initWithFilePath:(id)arg1;
- (id)initWithFilePath:(id)arg1 infoDictionary:(id)arg2;
- (id)commandLineToolSearchPath;

@end

