/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

@class DVTDispatchLock, DVTFilePath, DVTNotificationToken, DVTObservingToken, DVTPerformanceMetric, DVTPlaygroundCommunicationListener, IDEConsoleAdaptor, IDEPlaygroundExecutionParameters, IDEPlaygroundPreparationParameters, NSError, NSMutableArray, IDEConsoleAdaptor;

struct SBBreakpointLocation;

@interface IDEPlaygroundExecutionSession : NSOperation

+ (id)keyPathsForValuesAffectingCanFinishExecution;
+ (id)playgroundExecutionPerformanceLogAspect;
+ (id)playgroundExecutionLogAspect;
+ (id)executableSetupLock;
+ (void)initialize;
@property(copy) id handlePlaygroundDataBlock; 
@property(copy) id executionWillFinishBlock; 
@property(copy) id reportResultBlock; 
@property(retain) IDEPlaygroundExecutionParameters *executionParameters; 
@property(readonly) DVTFilePath *inProgressSerializationFilePath; 
@property(copy) id executableSetupBlock; 
@property(nonatomic) struct SBThread *executionBreakpointThread; 
@property BOOL consoleAdaptorIsOpen; 
@property BOOL playgroundListenerSerializationInProgress; 
@property BOOL playgroundListenerConnectionIsOpen; 
@property(retain) IDEConsoleAdaptor *targetConsoleAdaptor; 
@property int internalState; 
@property(retain) DVTFilePath *serializedPlaygroundDataPath; 
@property(retain) NSError *serializationError; 
@property(readonly) IDEPlaygroundPreparationParameters *preparationParameters; 
@property unsigned long long state; 

- (void)cleanupExecutable;
- (void)destroyDebugger;
- (void)_stopListeningForPlaygroundInput;
- (void)_interruptExecutingPlaygroundSource;
- (void)cancel;
- (BOOL)canFinishExecution;
- (void)undesignateSessionWithCallbackQueue:(id)arg1 callback:(id)arg2;
- (void)designateSessionForExecutionParameters:(id)arg1;
- (BOOL)playgroundExecutionWillFinishBreakpointHitOnThread:(struct SBThread *)arg1 location:(struct SBBreakpointLocation *)arg2;
- (void)_executePlaygroundSource;
- (BOOL)executePlaygroundBreakpointHitOnThread:(struct SBThread *)arg1 location:(struct SBBreakpointLocation *)arg2;
- (_Bool)shouldCancelExpressionEvaluationForPhase:(int)arg1;
- (void)_terminateProcess;
- (BOOL)handleInternalSessionEvent:(unsigned int)arg1;
- (BOOL)handleProcessEvent:(unsigned int)arg1;
- (void *)listenForEvents;
- (void)_setSessionThreadID:(struct _opaque_pthread_t *)arg1;
- (void)main;
- (id)_setupConsoleAdaptor;
- (void)_hookUpRealDataHandlingBlocks;
- (void)_flushPendingDataFromPreparation;
- (void)_setupPreparationDataHandlingBlocks;
- (void)_handleError:(id)arg1;
- (id)_generateSerializationFilePathWithError:(id *)arg1;
- (id)initWithPreparationParameters:(id)arg1 executableSetupBlock:(id)arg2 launcher:(void)arg3;

@end
