/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

@class DVTFilePath, DVTLineOffsetAwareStringWrapper, DVTSDK, IDEPlaygroundPreparationParameters, NSNumber, NSURL;

@interface IDEPlaygroundExecutionParameters : NSObject

@property(readonly) unsigned long long autoTerminationDelay;
@property(readonly) IDEPlaygroundPreparationParameters *preparationParameters;
@property(readonly) id playgroundExpressionCompleteBlock;
@property(readonly) id errorHandlerBlock;
@property(readonly) id executionWillFinishBlock;
@property(readonly) id reportResultBlock;
@property(readonly) NSNumber *documentContentTimestamp;
@property(readonly) NSURL *documentFileURL;
@property(readonly, copy) DVTLineOffsetAwareStringWrapper *sourceCodeToExecute;
@property(readonly) DVTSDK *sdk;
@property(readonly) DVTFilePath *executablePath;

- (id)initWithSourceCodeToExecute:(id)arg1 documentFileURL:(id)arg2 documentContentTimestamp:(id)arg3 autoTerminationDelay:(unsigned long long)arg4 executionPreparationParameters:(id)arg5 playgroundReportResultBlock:(id)arg6 playgroundExecutionWillFinishBlock:(void)arg7 playgroundExpressionCompleteBlock:(id)arg8 errorHandlerBlock:(void)arg9;

@end
