/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

@class DVTFilePath, DVTSDK, IDEPlaygroundExecutionDeviceService, NSString;

@interface IDEPlaygroundPreparationParameters : NSObject

@property(readonly) DVTFilePath *resourcesDirectoryPath;
@property(readonly, copy) NSString *playgroundName;
@property(readonly) DVTSDK *sdk;
@property(readonly) DVTFilePath *executablePath;
@property(readonly) IDEPlaygroundExecutionDeviceService *deviceService;

- (id)initWithExecutablePath:(NSString*)executablePath
                         sdk:(NSString*)sdk
               deviceService:(id)arg3
              playgroundName:(NSString*)playgroundName
      resourcesDirectoryPath:(NSString*)resourcesDirectoryPath;

@end

